name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build-project:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version.json
        run: |
          echo "{\"version\": \"${{ github.sha }}\"}" > public/version.json

      - name: Build App
        run: docker buildx build --platform linux/amd64,linux/arm64 -t triply.azurecr.io/triply-ui:${{ github.sha }} .

      - name: Login to Azure Container Registry
        if: github.ref == 'refs/heads/main'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}
          username: ${{ vars.ACR_TOKEN_USERNAME }}
          password: ${{ secrets.ACR_SECRET }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: docker push triply.azurecr.io/triply-ui:${{ github.sha }}

  deploy-to-azure:
    name: Deploy ACR image
    needs: build-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'triply'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          images: 'triply.azurecr.io/triply-ui:${{ github.sha }}'
