name: ci

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build App
        run: rm -rf .next && pnpm run build

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}
          username: ${{ vars.ACR_TOKEN_USERNAME }}
          password: ${{ secrets.ACR_SECRET }}

      - name: Build image
        run: docker build --no-cache -t triply.azurecr.io/triply-ui .
      - name: Push image
        run: docker push triply.azurecr.io/triply-ui
  deploy:
    name: Deploy ACR image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'triply'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          images: 'triply.azurecr.io/triply-ui'
